'\" t
.\"     Title: auto-multiple-choice
.\"    Author: Alexis Bienven\(:ue <paamc@passoire.fr>
.\"    Manual: Auto Multiple Choice
.\"  Language: English
.\"
.TH "AUTO\-MULTIPLE\-CHOICE" "1" "2025-07-04" "" "Auto Multiple Choice"
.SH "NAME"
auto-multiple-choice \- Automated treatment of MCQs
.SH "SYNOPSIS"
.HP \w'\fBauto\-multiple\-choice\fR\ 'u
\fBauto\-multiple\-choice\fR \fIaction\fR [arguments...]
.HP \w'\fBauto\-multiple\-choice\fR\ 'u
\fBauto\-multiple\-choice\fR [project]
.SH "DESCRIPTION"
.PP
The
\fBauto\-multiple\-choice\fR
command transmits its arguments to the
\fBAMC\-\fR\fB\fIaction\fR\fR\fB\&.pl\fR
command\&.
.PP
The second form, which does not mention any action, calls the graphical interface
\fBauto\-multiple\-choice gui\fR, possibly with the name of a project to be opened\&.
.SH "COPYRIGHT"
.br
Copyright \(co 2008-2025 Alexis Bienven\(:ue and the AMC development team.
.br
.PP
This document can be used according to the terms of the GNU General Public License, version 2 or later.
.sp
