# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: jojoboulix/amc-build

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - make version_files
          - make
          - make install && texhash
          - cd tests && make && ./all_tests --blind
          
