# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: jojoboulix/amc-build

pipelines:
  custom:
    test-and-tarball:
      - step:
          script: # Modify the commands below to build your repository.
            - make version_files
            - make
            - make install && texhash
            - make -C tests blind-test
            - make -C doc check
            - make sources
            - export TARBALL=auto-multiple-choice_$(hg log -r . --template '{latesttag}-{rev}-{node|short}')_dist.tar.gz
            - mv tarballs/auto-multiple-choice_*_precomp.tar.gz $TARBALL
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$TARBALL"
    tarball:
      - step:
          script: # Modify the commands below to build your repository.
            - make version_files
            - make sources
            - export TARBALL=auto-multiple-choice_$(hg log -r . --template '{latesttag}-{rev}-{node|short}')_dist.tar.gz
            - mv tarballs/auto-multiple-choice_*_precomp.tar.gz $TARBALL
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$TARBALL"
