# -*- makefile -*-
#
# Copyright (C) 2010 Alexis Bienvenue <paamc@passoire.fr>
#
# This file is part of Auto-Multiple-Choice
#
# Auto-Multiple-Choice is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 2 of
# the License, or (at your option) any later version.
#
# Auto-Multiple-Choice is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Auto-Multiple-Choice.  If not, see
# <http://www.gnu.org/licenses/>.

# SYSTEM FOR INSTALLATION

SYSTEM_TYPE ?= debian

# INSTALLATION : where to install parts of the package ?

# directory for executable
BINDIR=/usr/bin
# directory for perl modules
PERLDIR=/usr/share/perl5
# directory for some AMC executables, not to be used by end-user
MODSDIR=/usr/lib/AMC
# directory for LaTeX style file
TEXDIR=/usr/share/texmf-texlive/tex/latex/AMC
# directory for man (1) files
MAN1DIR=/usr/share/man/man1
# directory for desktop file 
DESKTOPDIR=/usr/share/applications
# directory for icons (svg)
ICONSDIR=/usr/share/auto-multiple-choice/icons
# directory for icons (xpm)
PIXDIR=/usr/share/pixmaps
# directory for locales (MO files will be put in
#                        $(LOCALEDIR)/fr/LC_MESSAGES for example)
LOCALEDIR=/usr/share/locale
# directory for AMC packaged models
MODELSDIR=/usr/share/auto-multiple-choice/models
# directory for documentation (will use html/auto-multiple-choice.* subdirs for HTML docs)
DOCDIR=/usr/share/doc/auto-multiple-choice

# BUILD : where to find some files used for building AMC ?
# URLs can be used if XML catalogs are present.

#DOCBOOK_MAN_XSL=/usr/share/xml/docbook/stylesheet/nwalsh/manpages/docbook.xsl
DOCBOOK_MAN_XSL=http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
#DOCBOOK_XHTML_XSL=/usr/share/xml/docbook/stylesheet/nwalsh/xhtml/chunk.xsl
DOCBOOK_XHTML_XSL=http://docbook.sourceforge.net/release/xsl/current/xhtml/chunk.xsl
#DOCBOOK_DTD=/usr/share/xml/docbook/schema/dtd/4.5/docbookx.dtd
DOCBOOK_DTD=http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd

# BUILD : options to compile with poppler / netpbm / opencv libraries

GCC_POPPLER=-I /usr/include/poppler -lpoppler

GCC_NETPBM=-lnetpbm

GCC_OPENCV=-I /usr/include/opencv -lcv -lhighgui

# INFO IN DESKTOP FILE

DESKTOP_CAT=Education;

# INSTALL USER AND GROUP

ifneq ($(SYSTEM_TYPE),rpm)
USER_GROUP=-o root -g root
endif

# DATE/TIME to be substituted

DATE_RPMCHL=$(shell LC_TIME=en_US date +"%a %b %e %Y")
DATE_DEBCHL=$(shell date -R)
