#! /bin/bash

RESULT_FILE=/tmp/amc-test.log
FAILS=0

for t in t/*/test.sh t/*/test.pl
do
  if $t --to-stdout $@ > $RESULT_FILE
  then
      echo -e "[ \e[0;32mOK\e[0m ] $t"
  else
      echo -e "[\e[0;31mFAIL\e[0m] $t"
      sed ' s/^/       /;' $RESULT_FILE
      FAILS=1
  fi
done

exit $FAILS
