#! /bin/bash

RESULT_FILE=/tmp/amc-test.log
FAILS=0

ARGS=$@

try_one() {
  t=$1
  if $t --to-stdout $ARGS > $RESULT_FILE
  then
      echo -e "[ \e[0;32mOK\e[0m ] $t"
      return 0
  else
      echo -e "[\e[0;31mFAIL\e[0m] $t"
      sed ' s/^/       /;' $RESULT_FILE
      return 1
  fi
}

for t in t/*/test.sh
do
    try_one $t || FAILS=1
done
for t in t/*/test.pl
do
    try_one "$PERLPATH $t" || FAILS=1
done

exit $FAILS
