#! /bin/sh

PROG_DIR=`dirname $0`

TARGZ=
SERIE=
EXT=

while [ "$#" -gt "0" ]
do
  case $1 in
      -t)
	  shift
	  TARGZ=$1
	  ;;
      -s)
	  shift
	  SERIE=$1
	  ;;
      -e)
	  shift
	  EXT=$1
	  ;;
      *)
	  echo "Syntax Error"
	  exit 1
	  ;;
  esac
  shift
done

if [ ! "$TARGZ" ];
then
    TARGZ=`$PROG_DIR/derniere-version.pl --extension tar.gz`
fi

if [ ! "$SERIE" ];
then
    SERIE=karmic
fi

if [ ! "$EXT" ];
then
    EXT=0ubuntu1
fi

TMPDIR=`mktemp -d`

echo "Je vais dans $TMPDIR..."

cd $TMPDIR

DIR=`tar xvzf $TARGZ | grep -E '^[^/]+/$'`

echo "Repertoire d'extraction : $DIR"

echo "Transformation du changelog..."

CHL=$TMPDIR/$DIR/debian/changelog

CHL_TEMP=$TMPDIR/changelog

cp $CHL $CHL_TEMP
sed -e "s/\\([0-9.]\\+\\)) unstable;/\\1-$EXT~ab~$SERIE) $SERIE;/;" $CHL_TEMP > $CHL

cd $DIR

echo "Empaquetage..."

debuild -S -sa -k42067447

ls -l $TMPDIR/*.changes

CHGF=`ls $TMPDIR/*.changes`

echo -e "*********************************************************************\n$CHGF\n*********************************************************************\n";

if [ -d "$TMPDIR/$DIR" ];
then
    echo "J'efface le repertoire d'extraction..."
    rm -r $TMPDIR/$DIR
fi

